### PR TITLE
Ansible Improvements and Reliability Adjustments

### PR DESCRIPTION
**Pull request by bencap**
This change contains Ansible improvements and adjustments to some tasks that improve our confidence that running them on production wouldn't create breaking changes.

First the improvements:
- Inventory simplification: This change moves our host list into yaml format and into a directory named `inventory`. This change was made in the interest of aligning us more closely with Ansible best practices and so that we could have all of our configurations in a common format.
- Crontab make: Added a task that makes backoffice crontabs.
- Logrotate configurations: This change adds modifications we've made on production to logrotate configurations to our Ansible configuration so that they are reproducible by running these playbooks.
- Husky Musher configurations: This change adds our Musher configuration to our playbooks.
- SFS Switchboard configurations: This change added the switchboard service file and added some additional configuration to ensure all file permissions were correct for the service.
- Task Tags: This change adds tags to tasks and task groups to make them easier to run individually and as logical configuration groupings. See the commit details of [here](https://github.com/seattleflu/infra/pull/18/commits/0a0f4489198b3ac4d482d08165862ddb517410a0) for additional detail.
- Registration task: This change adds a task that registers reused variables across tasks so that tasks can be run without depending on other tasks.
- Config cleanup: General cleanup on our configs to add and/or remove certain outdated or new configurations
- Docker install: We can now verify that docker is installed with Ansible
- SSL Cert: Added a task to verify key properties of our SSL certificate and a task to generate a self signed cert for local testing

And Confidence boosters:
- Python install tasks are limited in scope: The version of python was reset to our current prod version of 3.9.10 and the install was limited in scope. I personally still wouldn't run this on production at the moment (I don't _think_ it would break prod, but why risk it), but I think it is helpful for setting up local minimal environments.
- Postgres tasks are limited to package installs: The Postgres tasks are now limited to dev header install and postgres package installs. I confirmed locally installed packages are the same as those installed on prod, so we should be good there. Like Python, I don't see a point of running this on prod (and that is what the tags are for, but it is helpful for ensuring that development environments in Multipass are setup correctly.
- Apache2 tasks are limited to package installs: Mostly the same as above, didn't seem like there was a need for some of the other versions of Ubuntu at the moment, plus some of the Apache config copying was working off local versions of the repo, which could be dangerous if you happened to have a different branch checked out.

Let me know if there are any questions on testing this locally or on implementation details, I can definitely help out with the Multipass setup, testing runs, and on my thought process for some of the changes. Definitely don't want what happened last Friday happening again!

### CODE REVIEW

**Comment by bencap** [comment]
[Add tags to Ansible playbooks to better control which tasks run during deployments](https://trello.com/c/KRy0tih0/1418-add-tags-to-ansible-playbooks-to-better-control-which-tasks-run-during-deployments)

**Comment by bencap** [comment]
[Build up ansible playbooks](https://trello.com/c/8psx8dN5/984-build-up-ansible-playbooks)

**Review by kschwabefry — APPROVED** [review]
Thanks for all your thoughtful work on this @bencap, I know it was a big project to tackle!

**Comment by kschwabefry** [comment]
Gave the shib changes a read and they make sense to me! Thanks Ben.

**Comment by bencap** [comment]
Should also add postfix email config and rclone config setup.

**Comment by bencap** [comment]
Going to close this while we evaluate how we want to document our infrastructure underneath the new AWS environment.

**Pull request closed without merging**
